# Generated by Django 2.2.5 on 2019-11-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0001_initial'),
        ('appointments', '0002_auto_20191106_1714'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultfee',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultfee',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='bill',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillGroup'),
        ),
    ]
