# Generated by Django 2.2.5 on 2019-11-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advancederivatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivatives', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientalert', models.TextField()),
                ('visiabilitytype', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allerirs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergytype', models.CharField(blank=True, max_length=20, null=True)),
                ('allergien', models.CharField(blank=True, max_length=80, null=True)),
                ('reaction', models.TextField(blank=True, max_length=100, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amendments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendmentssource', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('statusdescription', models.CharField(max_length=150, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cptcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coodes', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cvxcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctornote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familyhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationtype', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('updtedon', models.DateTimeField(auto_now=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('fromdated', models.DateField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Healthhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('updtedon', models.DateTimeField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hspccodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icd10pcscodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icd10problemcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icdsymtomscodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='illnesssymtoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoncode', models.CharField(blank=True, max_length=50, null=True)),
                ('sysmtomdescription', models.TextField()),
                ('fromwhen', models.DateField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inpatientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admintdate', models.DateField()),
                ('dischargedate', models.DateField()),
                ('admissiontype', models.CharField(blank=True, max_length=50, null=True)),
                ('dischargesummary', models.TextField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabAssigntest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_group', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('codes', models.CharField(max_length=200, null=True)),
                ('cpt_code', models.CharField(max_length=200, null=True)),
                ('preferred_requiremen', models.CharField(max_length=200, null=True)),
                ('alternate_requirement', models.CharField(max_length=200, null=True)),
                ('transport_temperature', models.CharField(max_length=200, null=True)),
                ('methodology', models.CharField(max_length=200, null=True)),
                ('ref_range', models.CharField(max_length=200, null=True)),
                ('cost', models.CharField(max_length=200, null=True)),
                ('units', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lioniccode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicalcodesfordrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAllert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientalert', models.TextField()),
                ('visiabilitytype', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patientproblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('fromdate', models.DateField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthstatus', models.CharField(blank=True, max_length=150, null=True)),
                ('effectivedate', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositionName', models.CharField(blank=True, max_length=50, null=True)),
                ('doesage', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('withfood', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('usageDirection', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedurecodetype', models.CharField(blank=True, max_length=50, null=True)),
                ('procedurecode', models.CharField(blank=True, max_length=500, null=True)),
                ('procedure', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorcontact', models.CharField(blank=True, max_length=50, null=True)),
                ('doctoremail', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctornote', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reportfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socialhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('fromwhen', models.DateField()),
                ('updtedon', models.DateTimeField(auto_now=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symtomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icdcod', models.CharField(blank=True, max_length=500, null=True)),
                ('symtomdescription', models.CharField(blank=True, max_length=500, null=True)),
                ('fromdated', models.DateField()),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testsresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField()),
                ('ispaid', models.BooleanField(default=False)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
                ('testcode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takendate', models.DateField()),
                ('vaccinecode', models.TextField()),
                ('notes', models.TextField()),
                ('v_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitreson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('height_inch', models.FloatField(blank=True, null=True)),
                ('heartrate', models.FloatField(blank=True, null=True)),
                ('temprature', models.FloatField(blank=True, null=True)),
                ('oxisaturation', models.FloatField(blank=True, null=True)),
                ('diastolicbp', models.FloatField(blank=True, null=True)),
                ('systolicbp', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('resporitoryrate', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Appointment')),
            ],
        ),
    ]
