# Generated by Django 2.2.5 on 2019-11-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FloorNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.PositiveSmallIntegerField(choices=[(1, 'AC'), (2, 'NON-AC')])),
                ('occutype', models.CharField(blank=True, choices=[(1, 'Single'), (2, 'Double')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WardType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.IntegerField(unique=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('floorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.Floor')),
                ('roomtypeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.RoomType')),
                ('wardId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.wards')),
            ],
        ),
        migrations.CreateModel(
            name='FloorWardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.Floor')),
                ('wardid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.wards')),
            ],
        ),
        migrations.CreateModel(
            name='BedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedNum', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=0)),
                ('roomid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bms.RoomTable')),
            ],
        ),
        migrations.CreateModel(
            name='appointbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
                ('bedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.BedTable')),
            ],
        ),
    ]
