# Generated by Django 2.2.5 on 2019-11-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_auto_20191106_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointbed',
            old_name='bed',
            new_name='bedid',
        ),
    ]
