# Generated by Django 2.2.5 on 2019-11-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20191106_1714'),
        ('bms', '0003_auto_20191106_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointbed',
            new_name='AllotBed',
        ),
        migrations.RenameField(
            model_name='allotbed',
            old_name='bedid',
            new_name='bed',
        ),
    ]
